/**
 * Canonical product catalog for the 39 owner-required sections.
 * Availability is honesty-first — never mark SUMMARY_ONLY hubs as COMPLETE.
 */
import type { SectionIaGroup, SectionProductEntry } from "./types";

export const SECTION_IA_GROUPS: readonly SectionIaGroup[] = [
  {
    id: "quran-ulum",
    titleAr: "القرآن وعلومه",
    order: 1,
    sectionIds: [
      "quran-karim",
      "tajweed",
      "ulum-quran",
      "asbab-nuzul",
      "umam-sabiqa",
      "ijaz-ilmi",
    ],
  },
  {
    id: "sunnah-hadith",
    titleAr: "السنة والحديث",
    order: 2,
    sectionIds: ["hadith-ulum", "sunan-yawmiyya", "fadail-aamal", "dalail-nubuwwah"],
  },
  {
    id: "aqidah-seerah-history",
    titleAr: "العقيدة والسيرة والتاريخ",
    order: 3,
    sectionIds: [
      "aqidah",
      "seerah",
      "qasas-anbiya",
      "tarikh-islami",
      "firaq",
      "makarim-akhlaq",
      "adab-talab-ilm",
    ],
  },
  {
    id: "fiqh-usul-maqasid",
    titleAr: "الفقه وأصوله",
    order: 4,
    sectionIds: ["fiqh", "usul-fiqh", "maqasid", "sin-jeem", "wasaya"],
  },
  {
    id: "language-talib",
    titleAr: "اللغة وأدوات طالب العلم",
    order: 5,
    sectionIds: ["nahw-balagha", "research", "assistant"],
  },
  {
    id: "dawah-intro",
    titleAr: "التعريف والدعوة",
    order: 6,
    sectionIds: ["taarif-islam", "tafnid-shubuhat"],
  },
  {
    id: "lessons-institutions",
    titleAr: "الدروس والمؤسسات",
    order: 7,
    sectionIds: [
      "kuwait-lessons",
      "institutions",
      "historic-mosques",
      "universities",
      "lesson-reminders",
    ],
  },
  {
    id: "daily-worship",
    titleAr: "العبادة اليومية",
    order: 8,
    sectionIds: [
      "prayer-times",
      "adhan-reminders",
      "qibla",
      "adhkar",
      "duas",
      "tasbih",
      "fawaid",
    ],
  },
] as const;

/** Owner-required product sections (39). */
export const SECTION_PRODUCT_CATALOG: readonly SectionProductEntry[] = [
  {
    id: "kuwait-lessons",
    arabicName: "الدروس والدورات العلمية (الكويت)",
    englishName: "Kuwait lessons & courses",
    description: "دروس يومية وأسبوعية ودورات شهرية ببيانات أحداث موثّقة.",
    registrySectionId: "lessons",
    canonicalRoute: "/lessons",
    iaGroup: "lessons-institutions",
    learningType: "live_events",
    targetAudience: "طلاب العلم والزوار في الكويت وعن بُعد",
    availability: "LIVE_DATA",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "EVENT_SOURCES_PARTIAL",
    licenseStatus: "N/A_EVENTS",
    searchStatus: "PARTIAL",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: true,
    notificationSupport: true,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes:
      "Program 4 W1: contract docs + attendance/cancel/provenance fields. Seed still EVENT_SOURCES_PARTIAL (no lastVerifiedAt invented).",
  },
  {
    id: "sin-jeem",
    arabicName: "سين جيم",
    englishName: "Q&A challenge",
    description: "أسئلة وأجوبة تعليمية من بنوك معتمدة — بلا فتوى شخصية.",
    registrySectionId: "qa",
    canonicalRoute: "/qa",
    iaGroup: "fiqh-usul-maqasid",
    learningType: "quiz",
    targetAudience: "عامة المتعلمين",
    availability: "CURATED",
    publication: "CURATED_PUBLIC",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "QUIZ_BANK",
    licenseStatus: "INTERNAL",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: true,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Must never present AI answers as rulings.",
  },
  {
    id: "aqidah",
    arabicName: "العقيدة الإسلامية",
    englishName: "Islamic creed",
    description: "أصول الإيمان والتوحيد بمسارات موضوعية.",
    registrySectionId: "aqidah",
    canonicalRoute: "/tawhid",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "طلاب العلم والعامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED_EDITORIAL",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Needs structured curriculum completeness pass.",
  },
  {
    id: "seerah",
    arabicName: "السيرة النبوية",
    englishName: "Prophetic biography",
    description: "سيرة مرتّبة بمصادر، بلا حوارات مخترعة.",
    registrySectionId: "seerah",
    canonicalRoute: "/seerah",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Distinguish Quran/Hadith/history layers in later waves.",
  },
  {
    id: "qasas-anbiya",
    arabicName: "قصص الأنبياء",
    englishName: "Stories of the Prophets",
    description: "قصص بمصادر؛ بلا دراما مخترعة.",
    registrySectionId: "prophets",
    canonicalRoute: "/prophets",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "عامة والأسر",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Narration UI exists; content integrity gates apply.",
  },
  {
    id: "hadith-ulum",
    arabicName: "الحديث وعلومه",
    englishName: "Hadith & sciences",
    description: "مجموعات محلية + كتالوج؛ سجل مجموعات معتمد.",
    registrySectionId: "hadith",
    canonicalRoute: "/hadith",
    iaGroup: "sunnah-hadith",
    learningType: "reference",
    targetAudience: "طلاب الحديث والعامة",
    availability: "CURATED",
    publication: "CURATED_PUBLIC",
    contentCount: 14940,
    completeContentCount: null,
    sourceStatus: "REGISTRY_PINNED",
    licenseStatus: "PER_COLLECTION",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Hadith registry merged; full Sahihayn search still follow-up.",
  },
  {
    id: "tajweed",
    arabicName: "التجويد",
    englishName: "Tajweed",
    description: "مسارات تجويد تفاعلية بمصادر صوتية مرخّصة فقط.",
    registrySectionId: "quran-tajweed",
    canonicalRoute: "/quran-tajweed",
    iaGroup: "quran-ulum",
    learningType: "curriculum",
    targetAudience: "قرّاء ومتعلمون",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL",
    licenseStatus: "AUDIO_PENDING",
    searchStatus: "PARTIAL",
    offlineStatus: "UNKNOWN",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Program 7 progressive paths not yet complete.",
  },
  {
    id: "ulum-quran",
    arabicName: "علوم القرآن",
    englishName: "Quranic sciences",
    description: "علوم القرآن التعليمية.",
    registrySectionId: "ulum-quran",
    canonicalRoute: "/ulum-quran",
    iaGroup: "quran-ulum",
    learningType: "curriculum",
    targetAudience: "طلاب العلم",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Needs completeness contract on detail pages.",
  },
  {
    id: "quran-karim",
    arabicName: "القرآن الكريم / المصحف",
    englishName: "Quran / Mushaf",
    description: "مصحف وعلامات ومتابعة قراءة — بلا تعديل نص.",
    registrySectionId: "quran",
    canonicalRoute: "/mushaf",
    iaGroup: "quran-ulum",
    learningType: "hub",
    targetAudience: "جميع المستخدمين",
    availability: "OFFLINE_AVAILABLE",
    publication: "PUBLISHED",
    contentCount: 604,
    completeContentCount: 604,
    sourceStatus: "MUSHAF_PINNED",
    licenseStatus: "PROJECT_QURAN",
    searchStatus: "INDEXED",
    offlineStatus: "OFFLINE_READY",
    detailRouteStatus: "OK",
    progressSupport: true,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Bookmarks V2 shipped; never mutate Quran text.",
  },
  {
    id: "asbab-nuzul",
    arabicName: "أسباب النزول",
    englishName: "Occasions of revelation",
    description: "أسباب نزول بمراجع.",
    registrySectionId: "quran-asbab",
    canonicalRoute: "/quran-asbab",
    iaGroup: "quran-ulum",
    learningType: "reference",
    targetAudience: "طلاب التفسير",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "UNKNOWN",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Require pinned source editions before claiming COMPLETE.",
  },
  {
    id: "umam-sabiqa",
    arabicName: "الأمم السابقة",
    englishName: "Previous nations",
    description: "أمم سابقة من مصادر منضبطة.",
    registrySectionId: "nations",
    canonicalRoute: "/nations",
    iaGroup: "quran-ulum",
    learningType: "curriculum",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "No fabricated narratives.",
  },
  {
    id: "ijaz-ilmi",
    arabicName: "الإعجاز العلمي",
    englishName: "Scientific inimitability (disciplined)",
    description: "إعجاز منضبط بشفافية علمية — بلا مبالغة.",
    registrySectionId: "miracles",
    canonicalRoute: "/miracles",
    iaGroup: "quran-ulum",
    learningType: "reference",
    targetAudience: "عامة مع تنبيه منهجي",
    availability: "CURATED",
    publication: "CURATED_PUBLIC",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "SCIENTIFIC_PROVENANCE",
    licenseStatus: "MIXED",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Keep methodology warnings; scientific docs exist.",
  },
  {
    id: "fiqh",
    arabicName: "الفقه الإسلامي",
    englishName: "Islamic jurisprudence",
    description: "أبواب فقهية تعليمية — بلا فتوى فردية.",
    registrySectionId: "fiqh",
    canonicalRoute: "/fiqh",
    iaGroup: "fiqh-usul-maqasid",
    learningType: "curriculum",
    targetAudience: "طلاب الفقه والعامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Educational limitation banners required on rulings.",
  },
  {
    id: "tarikh-islami",
    arabicName: "التاريخ الإسلامي",
    englishName: "Islamic history",
    description: "تاريخ بتمحيص مصادر.",
    registrySectionId: "islamic-history",
    canonicalRoute: "/tarikh-islami",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "INDEXED",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "History search docs exist; still not full curriculum contract.",
  },
  {
    id: "firaq",
    arabicName: "الفرق الإسلامية",
    englishName: "Islamic sects",
    description: "قريبًا حتى اكتمال المصدر والسياسة المحايدة.",
    registrySectionId: "islamic-sects",
    canonicalRoute: "/islamic-sects",
    iaGroup: "aqidah-seerah-history",
    learningType: "reference",
    targetAudience: "طلاب العقيدة",
    availability: "COMING_SOON",
    publication: "COMING_SOON",
    contentCount: 0,
    completeContentCount: 0,
    sourceStatus: "BLOCKED_INCOMPLETE",
    licenseStatus: "UNKNOWN",
    searchStatus: "EXCLUDED",
    offlineStatus: "UNKNOWN",
    detailRouteStatus: "COMING_SOON",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "comingSoon=true in sections.registry; publish guards exist.",
  },
  {
    id: "maqasid",
    arabicName: "مقاصد الشريعة",
    englishName: "Maqasid",
    description: "مقاصد بمنهج تعليمي.",
    registrySectionId: "maqasid-sharia",
    canonicalRoute: "/maqasid-sharia",
    iaGroup: "fiqh-usul-maqasid",
    learningType: "curriculum",
    targetAudience: "طلاب الأصول",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "EDITORIAL_BODIES",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Accordion bodies exist; completeness contract still weak.",
  },
  {
    id: "usul-fiqh",
    arabicName: "أصول الفقه",
    englishName: "Usul al-Fiqh",
    description: "أصول الفقه التعليمية.",
    registrySectionId: "usul-fiqh",
    canonicalRoute: "/fiqh/usul",
    iaGroup: "fiqh-usul-maqasid",
    learningType: "curriculum",
    targetAudience: "طلاب العلم",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Fiqh door summaries exist; not full curriculum.",
  },
  {
    id: "makarim-akhlaq",
    arabicName: "مكارم الأخلاق",
    englishName: "Noble character",
    description: "أخلاق إسلامية.",
    registrySectionId: "akhlaq",
    canonicalRoute: "/akhlaq",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Needs structured lesson contract.",
  },
  {
    id: "dalail-nubuwwah",
    arabicName: "دلائل النبوة",
    englishName: "Proofs of prophethood",
    description: "دلائل بمصادر.",
    registrySectionId: "dalail-nubuwwah",
    canonicalRoute: "/dalail-nubuwwah",
    iaGroup: "sunnah-hadith",
    learningType: "curriculum",
    targetAudience: "عامة ودعوة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "EDITORIAL_BODIES",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Accordion depth gates exist; still not COMPLETE.",
  },
  {
    id: "taarif-islam",
    arabicName: "التعريف بالإسلام (متعدد اللغات)",
    englishName: "Introduction to Islam",
    description: "مسارات تعريف بترجمات معتمدة فقط.",
    registrySectionId: "discover-islam",
    canonicalRoute: "/discover-islam",
    iaGroup: "dawah-intro",
    learningType: "curriculum",
    targetAudience: "غير المسلمين والمسلم الجديد",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL_TRANSLATIONS",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: true,
    interactiveFeatureSupport: false,
    auditNotes: "Machine translation must not be final authority.",
  },
  {
    id: "tafnid-shubuhat",
    arabicName: "تفنيد الشبهات",
    englishName: "Responses to doubts",
    description: "أجوبة مصدرية — بلا ردود ذكاء اصطناعي غير مدعومة.",
    registrySectionId: "discover-islam",
    canonicalRoute: "/discover-islam",
    iaGroup: "dawah-intro",
    learningType: "reference",
    targetAudience: "عامة ودعوة",
    availability: "BLOCKED_INCOMPLETE",
    publication: "INTERNAL",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL_EMBEDDED",
    licenseStatus: "UNKNOWN",
    searchStatus: "EXCLUDED",
    offlineStatus: "UNKNOWN",
    detailRouteStatus: "HUB_ONLY",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Embedded in discover-islam; needs dedicated center + provenance.",
  },
  {
    id: "nahw-balagha",
    arabicName: "النحو والبلاغة",
    englishName: "Arabic grammar & rhetoric",
    description: "مركز لغة عربية؛ 95 درسًا حاليًا SUMMARY_ONLY.",
    registrySectionId: "arabic-language",
    canonicalRoute: "/arabic-language",
    iaGroup: "language-talib",
    learningType: "curriculum",
    targetAudience: "طلاب العربية",
    availability: "BLOCKED_INCOMPLETE",
    publication: "CURATED_PUBLIC",
    contentCount: 95,
    completeContentCount: 0,
    sourceStatus: "MISSING_SOURCE",
    licenseStatus: "UNKNOWN",
    searchStatus: "EXCLUDED",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Arabic Grammar W1 audit local; Wave 2 needs approved source for الإِعراب والبناء.",
  },
  {
    id: "institutions",
    arabicName: "دليل المؤسسات الإسلامية",
    englishName: "Islamic institutions directory",
    description: "دليل مؤسسات بمصادر رسمية.",
    registrySectionId: "islam-guide",
    canonicalRoute: "/islamic-directory",
    iaGroup: "lessons-institutions",
    learningType: "directory",
    targetAudience: "باحثون وطلاب",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes:
      "Nav SSOT: islam-guide → /islamic-directory. Child /institutions stays HIDDEN_FROM_NAV (no parallel seed).",
  },
  {
    id: "historic-mosques",
    arabicName: "دليل المساجد التاريخية",
    englishName: "Historic mosques directory",
    description: "مساجد تاريخية بمصادر وتحقق.",
    registrySectionId: "islam-guide",
    canonicalRoute: "/islamic-directory",
    iaGroup: "lessons-institutions",
    learningType: "directory",
    targetAudience: "عامة وباحثون",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes:
      "Nav SSOT: islam-guide → /islamic-directory. /islamic-landmarks and /mosques stay consolidated/hidden.",
  },
  {
    id: "research",
    arabicName: "الأبحاث العلمية",
    englishName: "Research center",
    description: "فهرسة أبحاث — بلا إعادة نشر محمية بلا إذن.",
    registrySectionId: "research",
    canonicalRoute: "/research",
    iaGroup: "language-talib",
    learningType: "directory",
    targetAudience: "باحثون",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "METADATA_ONLY",
    licenseStatus: "LINK_OUT",
    searchStatus: "PARTIAL",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Prefer metadata index when full-text not licensed.",
  },
  {
    id: "universities",
    arabicName: "دليل الجامعات والكليات الشرعية",
    englishName: "Sharia universities directory",
    description: "جامعات وبرامج من مصادر رسمية فقط.",
    registrySectionId: "universities",
    canonicalRoute: "/universities",
    iaGroup: "lessons-institutions",
    learningType: "directory",
    targetAudience: "طلاب جامعيون",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "PARTIAL",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Never fabricate accreditation.",
  },
  {
    id: "adhkar",
    arabicName: "الأذكار",
    englishName: "Adhkar",
    description: "أذكار يومية بمصادر.",
    registrySectionId: "adhkar",
    canonicalRoute: "/adhkar",
    iaGroup: "daily-worship",
    learningType: "worship",
    targetAudience: "عامة",
    availability: "CURATED",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "CURATED",
    licenseStatus: "INTERNAL",
    searchStatus: "INDEXED",
    offlineStatus: "OFFLINE_READY",
    detailRouteStatus: "OK",
    progressSupport: true,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Unify with duas/tasbih/sunan in Program 17.",
  },
  {
    id: "wasaya",
    arabicName: "الوصايا",
    englishName: "Prophetic counsels",
    description: "وصايا نبوية.",
    registrySectionId: "wasaya-nabawiyya",
    canonicalRoute: "/wasaya-nabawiyya",
    iaGroup: "fiqh-usul-maqasid",
    learningType: "reference",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Need source attribution pass.",
  },
  {
    id: "fadail-aamal",
    arabicName: "فضائل الأعمال",
    englishName: "Virtues of deeds",
    description: "فضائل بأسانيد/درجات حيث تتوفر.",
    registrySectionId: "fadail-aamal",
    canonicalRoute: "/fadail-aamal",
    iaGroup: "sunnah-hadith",
    learningType: "reference",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "No unsupported reward claims.",
  },
  {
    id: "sunan-yawmiyya",
    arabicName: "السنن النبوية اليومية",
    englishName: "Daily Sunnah",
    description: "سنن يومية.",
    registrySectionId: "sunan-yawmiyya",
    canonicalRoute: "/sunan-yawmiyya",
    iaGroup: "sunnah-hadith",
    learningType: "worship",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: true,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Unify completion state with adhkar.",
  },
  {
    id: "adab-talab-ilm",
    arabicName: "آداب طالب العلم",
    englishName: "Etiquette of seeking knowledge",
    description: "آداب طلب العلم.",
    registrySectionId: "adab-talab-ilm",
    canonicalRoute: "/adab-talab-ilm",
    iaGroup: "aqidah-seerah-history",
    learningType: "curriculum",
    targetAudience: "طلاب العلم",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "MIXED",
    licenseStatus: "UNKNOWN",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Registered in sections.registry; curriculum completeness still PARTIAL (not COMPLETE).",
  },
  {
    id: "fawaid",
    arabicName: "الفوائد المنتقاة",
    englishName: "Selected benefits",
    description: "فوائد منتقاة.",
    registrySectionId: "fawaid",
    canonicalRoute: "/fawaid",
    iaGroup: "daily-worship",
    learningType: "reference",
    targetAudience: "عامة",
    availability: "CURATED",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "CURATED",
    licenseStatus: "INTERNAL",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: false,
    auditNotes: "Curated feed; provenance per item varies.",
  },
  {
    id: "duas",
    arabicName: "الأدعية",
    englishName: "Supplications",
    description: "أدعية بمصادر.",
    registrySectionId: "duas",
    canonicalRoute: "/duas",
    iaGroup: "daily-worship",
    learningType: "worship",
    targetAudience: "عامة",
    availability: "CURATED",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "CURATED",
    licenseStatus: "INTERNAL",
    searchStatus: "PARTIAL",
    offlineStatus: "OFFLINE_READY",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: true,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Unify with adhkar program.",
  },
  {
    id: "tasbih",
    arabicName: "التسبيح",
    englishName: "Tasbeeh counter",
    description: "عدّاد تسبيح.",
    registrySectionId: "tasbih",
    canonicalRoute: "/tasbih",
    iaGroup: "daily-worship",
    learningType: "tool",
    targetAudience: "عامة",
    availability: "COMPLETE",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "N/A_TOOL",
    licenseStatus: "N/A",
    searchStatus: "PARTIAL",
    offlineStatus: "OFFLINE_READY",
    detailRouteStatus: "OK",
    progressSupport: true,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Tool completeness ≠ content encyclopedia.",
  },
  {
    id: "qibla",
    arabicName: "القبلة",
    englishName: "Qibla",
    description: "اتجاه القبلة.",
    registrySectionId: "qibla",
    canonicalRoute: "/qibla",
    iaGroup: "daily-worship",
    learningType: "tool",
    targetAudience: "عامة",
    availability: "COMPLETE",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "N/A_TOOL",
    licenseStatus: "N/A",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Device sensors; DEVICE_REQUIRED validation.",
  },
  {
    id: "prayer-times",
    arabicName: "مواقيت الصلاة",
    englishName: "Prayer times",
    description: "مواقيت وعدّ تنازلي — بلا وميض أبيض.",
    registrySectionId: "prayer",
    canonicalRoute: "/prayer-times",
    iaGroup: "daily-worship",
    learningType: "tool",
    targetAudience: "عامة",
    availability: "LIVE_DATA",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "CALCULATION_ENGINE",
    licenseStatus: "N/A",
    searchStatus: "PARTIAL",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: true,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Do not change calculation algorithms without dedicated tests.",
  },
  {
    id: "lesson-reminders",
    arabicName: "تنبيهات الدروس",
    englishName: "Lesson reminders",
    description: "تذكير بالدروس المحفوظة/القادمة.",
    registrySectionId: "notifications",
    canonicalRoute: "/notifications",
    iaGroup: "lessons-institutions",
    learningType: "tool",
    targetAudience: "متابعو الدروس",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "APP_NOTIFICATIONS",
    licenseStatus: "N/A",
    searchStatus: "EXCLUDED",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: true,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Avoid duplicate schedules; permission states required.",
  },
  {
    id: "adhan-reminders",
    arabicName: "تنبيهات الأذان",
    englishName: "Adhan reminders",
    description: "إعدادات وتنبيهات الأذان.",
    registrySectionId: "athan-settings",
    canonicalRoute: "/athan-settings",
    iaGroup: "daily-worship",
    learningType: "tool",
    targetAudience: "عامة",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "APP_NOTIFICATIONS",
    licenseStatus: "N/A",
    searchStatus: "EXCLUDED",
    offlineStatus: "PARTIAL",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: true,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Native sound assets must stay in bundle resources.",
  },
  {
    id: "assistant",
    arabicName: "المساعد العلمي",
    englishName: "Scientific assistant",
    description: "مساعد استرجاعي — بلا اختراع أحكام.",
    registrySectionId: "assistant",
    canonicalRoute: "/assistant",
    iaGroup: "language-talib",
    learningType: "assistant",
    targetAudience: "جميع المستخدمين",
    availability: "PARTIAL",
    publication: "PUBLISHED",
    contentCount: null,
    completeContentCount: null,
    sourceStatus: "RETRIEVAL_FIRST",
    licenseStatus: "N/A",
    searchStatus: "EXCLUDED",
    offlineStatus: "NETWORK_REQUIRED",
    detailRouteStatus: "OK",
    progressSupport: false,
    bookmarkSupport: false,
    notificationSupport: false,
    multilingualSupport: false,
    interactiveFeatureSupport: true,
    auditNotes: "Must expose sources + limitation when no approved hit.",
  },
] as const;

export const REQUIRED_SECTION_COUNT = 39;
