/** نصوص التسميع داخل المصحف. */
export const T = {
  fabStart: "ابدأ التسميع",
  fabRecord: "ابدأ التسجيل",
  fabStop: "أوقف التسجيل",
  timer: "مدة التسجيل",
  toolbar: "أدوات التسميع",
  errors: "أخطاء",
  viewMode: "نمط العرض: تركيز على الآية الحالية",
  hideAyahs: "إخفاء الآيات",
  hideOn: "الآيات المخفية: مفعّل",
  hideOff: "الآيات المخفية: متوقف",
  backWord: "رجوع كلمة",
  backAyah: "رجوع آية",
  restart: "من بداية المقطع",
  revealNext: "إظهار الكلمة التالية",
  alertSettings: "تنبيهات الأخطاء",
  modesTitle: "الوضع",
  modes: { listen: "استماع", tasmee: "تسميع", test: "اختبار" },
  modeHints: {
    listen: "",
    tasmee: "اقرأ من حفظك وتظهر الكلمات الصحيحة في موضعها",
    test: "",
  },
  modeSoon: {
    listen: "يتوفر عند جاهزية الصوت المرخّص",
    tasmee: "",
    test: "يتوفر قريبًا",
  },
  exit: "إنهاء التسميع",
  alertsTitle: "تنبيهات الأخطاء",
  redShade: "تظليل أحمر",
  haptic: "اهتزاز خفيف",
  tone: "نغمة قصيرة",
  timing: "وقت التنبيه",
  instant: "تنبيه فوري",
  afterSegment: "بعد انتهاء المقطع",
} as const;
