/**
 * PR S6 — عقد دخولية iOS الأصلية + منع انجراف المرآة العامة.
 * تشغيل: node --import tsx src/lib/__tests__/startup-ios-native-splash-s6-gate.test.ts
 *
 * ملاحظة: ios/App/App/public/** gitignored (ما عدا .gitkeep) ويُملأ بـ cap sync.
 * مصدر الحقيقة للمرآة: public/mj-launch-splash-boot.js — المقارنة البايتية محلية عند وجود المرآة.
 */
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const majalisRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const repoRoot = resolve(majalisRoot, "../..");
const readPkg = (rel: string) => readFileSync(resolve(majalisRoot, rel), "utf8");
const readRepo = (rel: string) => readFileSync(resolve(repoRoot, rel), "utf8");

const LIGHT = "#F8F6F1";
const DARK = "#101614";

const contractDoc = readRepo("docs/performance/IOS_NATIVE_SPLASH_CONTRACT.md");
assert.match(contractDoc, /IOS_NATIVE_SPLASH_CONTRACT/);
assert.match(contractDoc, /WEB_SPLASH_CONTRACT/);
assert.match(contractDoc, /IOS_PUBLIC_MIRROR/);
assert.match(contractDoc, /PHYSICAL_IOS_STARTUP_VALIDATION_REQUIRED/);
assert.match(contractDoc, /cap sync|gitignore/i);
assert.match(contractDoc, new RegExp(LIGHT.replace("#", "#?")));
assert.doesNotMatch(contractDoc, /ZERO_FLICKER_ON_IOS\s*=\s*PASS/);

const splashTs = readPkg("src/lib/majlis-splash.ts");
assert.match(splashTs, new RegExp(`SPLASH_BG_LIGHT\\s*=\\s*"${LIGHT}"`));
assert.match(splashTs, new RegExp(`SPLASH_BG_DARK\\s*=\\s*"${DARK}"`));

const indexHtml = readPkg("index.html");
assert.match(indexHtml, new RegExp(`--mj-splash-bg-light:\\s*${LIGHT}`, "i"));
assert.match(indexHtml, new RegExp(`--mj-splash-bg-dark:\\s*${DARK}`, "i"));
assert.match(indexHtml, new RegExp(`theme-color" content="${LIGHT}"`));
assert.doesNotMatch(indexHtml, /#F7F3EB/i);

for (const rel of [
  "capacitor.config.ts",
  "capacitor.config.json",
  "ios/App/App/capacitor.config.json",
]) {
  const cfg = readPkg(rel);
  assert.match(cfg, new RegExp(`backgroundColor["']?\\s*[:=]\\s*["']${LIGHT}["']`), rel);
  assert.doesNotMatch(cfg, /#F7F3EB/i, `${rel}: legacy beige retired`);
}

const colorset = JSON.parse(
  readPkg("ios/App/App/Assets.xcassets/LaunchBackground.colorset/Contents.json"),
);
const colors = colorset.colors as Array<{
  appearances?: Array<{ value?: string }>;
  color: { components: { red: string; green: string; blue: string } };
}>;
const light = colors.find((c) => !c.appearances)?.color.components;
const dark = colors.find((c) => c.appearances?.some((a) => a.value === "dark"))?.color.components;
assert.ok(light, "LaunchBackground light");
/* LaunchScreen فاتح فقط = خلفية WKWebView (ios.backgroundColor) = الويب الافتراضي — الداكن كان يومض داكن→فاتح */
assert.equal(dark, undefined, "LaunchBackground بلا متغيّر ليلي");
const near = (a: string, b: number, tol = 0.004) => Math.abs(Number(a) - b) <= tol;
/* #F8F6F1 = 248,246,241 /255 */
assert.ok(near(light!.red, 248 / 255) && near(light!.green, 246 / 255) && near(light!.blue, 241 / 255), "light ≈ F8F6F1");
/* #101614 = 16,22,20 /255 */

const storyboard = readPkg("ios/App/App/Base.lproj/LaunchScreen.storyboard");
assert.match(storyboard, /name="LaunchBackground"/);
assert.doesNotMatch(storyboard, /systemBackgroundColor/i);
assert.doesNotMatch(storyboard, /<imageView\b/i);
assert.doesNotMatch(storyboard, /<label\b/i);
assert.match(storyboard, /0\.9725490196078431|0\.973/, "storyboard light red ≈ F8F6F1");

const webBoot = readPkg("public/mj-launch-splash-boot.js");
assert.match(webBoot, /MIN_MS\s*=\s*0/);
assert.match(webBoot, /__mjDismissSplash/);
assert.match(indexHtml, /src="\/mj-launch-splash-boot\.js"/);

const capTs = readPkg("capacitor.config.ts");
assert.match(capTs, /webDir:\s*["']dist["']/, "cap sync source = dist (includes public boot)");
assert.match(capTs, /launchAutoHide:\s*false/);
assert.match(capTs, /launchShowDuration:\s*0/);

const iosGitignore = readPkg("ios/.gitignore");
assert.match(iosGitignore, /App\/App\/public\/\*\*/);
assert.match(iosGitignore, /!App\/App\/public\/\.gitkeep/);

const iosBootPath = resolve(majalisRoot, "ios/App/App/public/mj-launch-splash-boot.js");
if (existsSync(iosBootPath)) {
  const iosBoot = readFileSync(iosBootPath, "utf8");
  assert.equal(webBoot, iosBoot, "IOS_PUBLIC_MIRROR byte-identical when present after sync");
} else {
  /* CI clean clone: mirror regenerated by cap sync from dist/public — pipeline contract above */
  assert.ok(true, "IOS_PUBLIC_MIRROR deferred to cap sync (gitignored)");
}

const splashCtrl = readPkg("src/lib/splash-screen.ts");
assert.match(splashCtrl, /armNativeSplashController/);
assert.match(splashCtrl, /startup:native-end/);
assert.match(splashCtrl, /mj:shell-stable/);
assert.match(splashCtrl, /hideCapacitorSplash\(true\)/);

const site = JSON.parse(readPkg("site.config.json"));
assert.equal(site.themeColor, LIGHT, "site.config themeColor aligned");

const pkg = readPkg("package.json");
assert.match(pkg, /"test:startup-ios-native-splash-s6"/);

console.log("IOS_NATIVE_SPLASH_CONTRACT_ALIGNED");
console.log("WEB_NATIVE_SPLASH_DRIFT_PREVENTED");
console.log("PHYSICAL_IOS_STARTUP_VALIDATION_REQUIRED");
console.log("startup-ios-native-splash-s6-gate: ok");
