export type WidgetCenterCatalogItem = {
  kind: string;
  nameAr: string;
  descriptionAr: string;
  families: string[];
  dataRequirementsAr: string;
  configurationAr: string;
  privacyClass: "public-safe" | "local-progress";
  requiresAppOpen: boolean;
  deepLink: string;
  section: "prayer" | "calendar" | "adhkar" | "quran" | "content" | "home";
};

export const WIDGET_CENTER_CATALOG: WidgetCenterCatalogItem[] = [
  { kind: "PrayerTimesWidget", nameAr: "مواقيت الصلاة", descriptionAr: "الصلاة التالية والعد التنازلي.", families: ["صغير", "متوسط", "كبير", "قفل"], dataRequirementsAr: "لقطة المواقيت المنشورة", configurationAr: "موقع ومدينة الصلاة", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.current", nameAr: "الصلاة الحالية", descriptionAr: "الصلاة الجارية ووقت بدايتها والمنقضي.", families: ["صغير", "متوسط", "قفل مستطيل"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.next", nameAr: "الصلاة التالية", descriptionAr: "العد التنازلي الكبير مع التاريخ الهجري.", families: ["صغير", "متوسط", "كبير", "قفل"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "نمط العرض", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.previous", nameAr: "الصلاة السابقة", descriptionAr: "آخر صلاة دخل وقتها اليوم.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.hijri", nameAr: "صلاة مع التاريخ", descriptionAr: "الصلاة التالية مع اليوم الهجري.", families: ["صغير", "متوسط"], dataRequirementsAr: "لقطة المواقيت + تقويم", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.previous-next", nameAr: "السابقة والتالية", descriptionAr: "الصلاة السابقة والتالية مع العد.", families: ["متوسط", "كبير"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.morning", nameAr: "فجر وشروق وظهر", descriptionAr: "مجموعة صلاة الصباح.", families: ["صغير", "متوسط"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "مجموعة الصباح", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.evening", nameAr: "عصر ومغرب وعشاء", descriptionAr: "مجموعة صلاة المساء.", families: ["صغير", "متوسط"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "مجموعة المساء", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.prayer.all", nameAr: "مواقيت اليوم", descriptionAr: "الأوقات الستة.", families: ["كبير"], dataRequirementsAr: "لقطة المواقيت", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/prayer-times", section: "prayer" },
  { kind: "sunnah.widget.calendar.hijri", nameAr: "التاريخ الهجري", descriptionAr: "اليوم والشهر الهجري وفق أم القرى.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "تقويم منشور", configurationAr: "نمط هجري", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/occasions", section: "calendar" },
  { kind: "sunnah.widget.calendar.dual", nameAr: "هجري وميلادي", descriptionAr: "تاريخان معاً.", families: ["صغير", "متوسط"], dataRequirementsAr: "تقويم منشور", configurationAr: "نمط مزدوج", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/occasions", section: "calendar" },
  { kind: "sunnah.widget.calendar.today", nameAr: "يومك", descriptionAr: "اليوم الهجري والميلادي مع المناسبة إن وُجدت.", families: ["متوسط", "كبير"], dataRequirementsAr: "تقويم منشور", configurationAr: "نمط مزدوج", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/occasions", section: "calendar" },
  { kind: "sunnah.widget.calendar.ramadan", nameAr: "عداد رمضان", descriptionAr: "الأيام المتبقية أو حالة الشهر.", families: ["صغير", "متوسط"], dataRequirementsAr: "تقويم منشور", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/occasions", section: "calendar" },
  { kind: "sunnah.widget.calendar.event", nameAr: "المناسبة القادمة", descriptionAr: "مناسبة مراجعة مع حالة التأكيد.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "سجل شرعي قابل للنشر", configurationAr: "لا مناسبات خلافية", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/occasions", section: "calendar" },
  { kind: "sunnah.widget.adhkar.morning", nameAr: "أذكار الصباح", descriptionAr: "مدخل سريع لورد الصباح.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "مستودع الأذكار", configurationAr: "فئة الصباح", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/adhkar/morning", section: "adhkar" },
  { kind: "sunnah.widget.adhkar.evening", nameAr: "أذكار المساء", descriptionAr: "مدخل سريع لورد المساء.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "مستودع الأذكار", configurationAr: "فئة المساء", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/adhkar/evening", section: "adhkar" },
  { kind: "sunnah.widget.adhkar.time-aware", nameAr: "أذكار الوقت", descriptionAr: "المجموعة حسب نافذة سُنّة المعتمدة.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "سياق الوقت + الأذكار", configurationAr: "حسب الوقت", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/adhkar", section: "adhkar" },
  { kind: "sunnah.widget.adhkar.rotating", nameAr: "ذكر اليوم", descriptionAr: "ذكر معتمد يتجدد يومياً.", families: ["صغير", "متوسط"], dataRequirementsAr: "ذكر يومي مراجع", configurationAr: "إظهار المصدر", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/adhkar", section: "adhkar" },
  { kind: "sunnah.widget.adhkar.streak", nameAr: "سلسلة الأذكار", descriptionAr: "إنجاز اليوم والسلسلة إن وُجد تتبع.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "تتبع يومي معتمد", configurationAr: "لا تُختلق سلسلة", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/adhkar", section: "adhkar" },
  { kind: "sunnah.widget.quran.ayah", nameAr: "آية اليوم", descriptionAr: "نص آية معتمد كما هو.", families: ["متوسط", "كبير"], dataRequirementsAr: "مستودع القرآن + دورة مراجعة", configurationAr: "دورة معتمدة", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/mushaf", section: "quran" },
  { kind: "sunnah.widget.quran.goal", nameAr: "هدف القرآن", descriptionAr: "هدف اليوم إن وُجد تتبع.", families: ["صغير", "متوسط", "قفل"], dataRequirementsAr: "daily-progress", configurationAr: "تفعيل التتبع", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/quran-hub", section: "quran" },
  { kind: "sunnah.widget.mushaf.continue", nameAr: "متابعة المصحف", descriptionAr: "آخر موضع محفوظ.", families: ["صغير", "متوسط"], dataRequirementsAr: "lastPage", configurationAr: "لا اختراع لصفحة ١", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/mushaf", section: "quran" },
  { kind: "sunnah.widget.mushaf.bookmark", nameAr: "إشارة المصحف", descriptionAr: "الإشارة التي اخترتها.", families: ["صغير", "متوسط"], dataRequirementsAr: "فواصل المصحف", configurationAr: "اختيار إشارة", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/mushaf/bookmarks", section: "quran" },
  { kind: "sunnah.widget.mushaf.progress", nameAr: "موضع المصحف", descriptionAr: "آخر صفحة محفوظة دون نسبة مخترعة.", families: ["صغير", "متوسط"], dataRequirementsAr: "lastPage", configurationAr: "لا اختراع لصفحة ١", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/mushaf", section: "quran" },
  { kind: "sunnah.widget.mushaf.quick-open", nameAr: "افتح المصحف", descriptionAr: "هدف كبير لآخر موضع.", families: ["صغير", "متوسط", "كبير"], dataRequirementsAr: "lastPage أو الفاتحة كبداية لا كتقدم", configurationAr: "لا", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/mushaf", section: "quran" },
  { kind: "sunnah.widget.content.hadith", nameAr: "حديث اليوم", descriptionAr: "حديث قصير معتمد مع المصدر.", families: ["صغير", "متوسط", "كبير"], dataRequirementsAr: "حوض الحديث المراجع", configurationAr: "إظهار المصدر", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/hadith", section: "content" },
  { kind: "sunnah.widget.content.faidah", nameAr: "فائدة اليوم", descriptionAr: "فائدة مراجعة مع المصدر.", families: ["صغير", "متوسط"], dataRequirementsAr: "حوض الفوائد المنشور", configurationAr: "إظهار المصدر", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/", section: "content" },
  { kind: "sunnah.widget.content.dua", nameAr: "دعاء اليوم", descriptionAr: "دعاء معتمد كامل المعنى.", families: ["صغير", "متوسط", "كبير"], dataRequirementsAr: "أذكار/أدعية قابلة للنشر", configurationAr: "إظهار المصدر", privacyClass: "public-safe", requiresAppOpen: false, deepLink: "/adhkar", section: "content" },
  { kind: "sunnah.widget.custom", nameAr: "محتوى اختياري", descriptionAr: "آية أو حديث أو ذكر أو دعاء تختاره.", families: ["صغير", "متوسط", "كبير"], dataRequirementsAr: "سجل اختيار محلي", configurationAr: "App Intent لكل نسخة", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/widget-center", section: "content" },
  { kind: "sunnah.widget.home.today", nameAr: "اليوم في سُنّة", descriptionAr: "صلاة وأذكار وهدف قراءة.", families: ["متوسط", "كبير"], dataRequirementsAr: "صلاة + أذكار + تتبع اختياري", configurationAr: "لا", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/", section: "home" },
  { kind: "sunnah.widget.home.actions", nameAr: "اختصارات اليوم", descriptionAr: "صلاة، أذكار، مصحف، قرآن.", families: ["متوسط", "كبير"], dataRequirementsAr: "روابط عميقة فقط", configurationAr: "لا", privacyClass: "public-safe", requiresAppOpen: true, deepLink: "/", section: "home" },
  { kind: "sunnah.widget.home.spiritual", nameAr: "اليوم الروحي", descriptionAr: "إتمام معتمد لا نسب مخترعة.", families: ["متوسط", "كبير"], dataRequirementsAr: "تتبع يومي معتمد", configurationAr: "تفعيل التتبع", privacyClass: "local-progress", requiresAppOpen: true, deepLink: "/progress", section: "home" },
];
